/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package fr.jaxio.demo.web.selenium.page.more.moretypesdemo;

import static org.openqa.selenium.By.cssSelector;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import fr.jaxio.demo.web.selenium.support.Page;
import fr.jaxio.demo.web.selenium.page.AbstractSearchPage;

@Page
public class MoreTypesDemoSearchPage extends AbstractSearchPage {
    // search box
    @FindBy(id = "form:numberInt")
    public WebElement numberInt;
    @FindBy(id = "form:numberLong")
    public WebElement numberLong;
    @FindBy(id = "form:numberDouble")
    public WebElement numberDouble;
    @FindBy(id = "form:numberFloat")
    public WebElement numberFloat;
    @FindBy(id = "form:numberBigInteger")
    public WebElement numberBigInteger;
    @FindBy(id = "form:numberBigDecimal")
    public WebElement numberBigDecimal;
    @FindBy(id = "form:dateJavaTemporalDate")
    public WebElement dateJavaTemporalDate;
    @FindBy(id = "form:dateJavaTemporalTimestamp")
    public WebElement dateJavaTemporalTimestamp;
    @FindBy(id = "form:dateJoda")
    public WebElement dateJoda;
    @FindBy(id = "form:dateTimeJoda")
    public WebElement dateTimeJoda;

    public void clickEditMoreTypesDemo(String moreTypesDemo) {
        client.click(cssSelector("button[title=\"Edit " + moreTypesDemo + "\"]"));
    }

    public void clickAddMoreTypesDemo(String moreTypesDemo) {
        client.click(cssSelector("button[title=\"Add " + moreTypesDemo + "\"]"));
    }

    public void clickDeleteMoreTypesDemo(String moreTypesDemo) {
        client.click(cssSelector("button[title=\"Delete " + moreTypesDemo + "\"]"));
    }

    public void clickSelectMoreTypesDemo(String moreTypesDemo) {
        client.click(cssSelector("button[title=\"Select " + moreTypesDemo + "\"]"));
    }
}