/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/SearchForm.e.vm.java
 */
package com.company.demo.web.controller;

import static com.google.common.collect.Lists.newArrayList;

import java.io.Serializable;
import java.util.List;
import com.company.demo.domain.Legacy;
import com.company.demo.repository.support.NullRestriction;
import com.company.demo.repository.support.SearchForm;

/**
 * SearchForm for {@link LegacyService}
 */
public class LegacySearchForm extends SearchForm<Legacy> implements Serializable {
    private static final long serialVersionUID = 1L;

    private Legacy legacy = new Legacy();

    /**
     * The root legacy for search by example.
     * Used from the view.
     */
    @Override
    public Legacy getForm() {
        return legacy;
    }

    public Legacy getLegacy() {
        return getForm();
    }

    @Override
    public List<NullRestriction> getNullRestrictions() {
        List<NullRestriction> result = newArrayList();
        return result;
    }
}