/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/SearchForm.e.vm.java
 */
package com.jaxio.demo.web.controller;

import static com.google.common.collect.Lists.newArrayList;

import static com.jaxio.demo.domain.Account_.*;
import java.io.Serializable;
import java.util.List;
import com.jaxio.demo.domain.Account;
import com.jaxio.demo.repository.support.Range;
import com.jaxio.demo.repository.support.Ranges.RangeDate;
import com.jaxio.demo.web.util.NullRestriction;
import com.jaxio.demo.web.util.SearchForm;

/**
 * SearchForm for {@link AccountService}
 */
public class AccountSearchForm extends SearchForm<Account> implements Serializable {
    private static final long serialVersionUID = 1L;

    private Account account = new Account();
    private RangeDate<Account> birthDateRange = new RangeDate<Account>(birthDate);

    /**
     * The root account for search by example.
     * Used from the view.
     */
    public Account getAccount() {
        return account;
    }

    // Ranges, used from the view.

    public RangeDate<Account> getBirthDateRange() {
        return birthDateRange;
    }

    @Override
    public List<Range<Account, ?>> getRanges() {
        List<Range<Account, ?>> result = newArrayList();
        result.add(getBirthDateRange());
        return result;
    }

    private NullRestriction homeAddressNullRestriction = new NullRestriction("homeAddress");

    public NullRestriction getHomeAddressNullRestriction() {
        return homeAddressNullRestriction;
    }

    @Override
    public List<NullRestriction> getNullRestrictions() {
        List<NullRestriction> result = newArrayList();
        result.add(homeAddressNullRestriction);
        return result;
    }
}