/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3-sd:src/main/java/web/controller/SearchForm.e.vm.java
 */
package com.jaxio.demo.web.controller;

import static com.google.common.collect.Lists.newArrayList;

import java.io.Serializable;
import java.util.List;
import com.jaxio.demo.domain.Role;
import com.jaxio.demo.web.util.NullRestriction;
import com.jaxio.demo.web.util.SearchForm;

/**
 * SearchForm for {@link RoleService}
 */
public class RoleSearchForm extends SearchForm<Role> implements Serializable {
    private static final long serialVersionUID = 1L;

    private Role role = new Role();

    /**
     * The root role for search by example.
     * Used from the view.
     */
    public Role getRole() {
        return role;
    }

    @Override
    public List<NullRestriction> getNullRestrictions() {
        List<NullRestriction> result = newArrayList();
        return result;
    }
}