/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.jaxio.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.domain.Account;
import com.jaxio.domain.Currency;
import com.jaxio.domain.Customer;
import com.jaxio.repository.CurrencyGenerator;
import com.jaxio.repository.CurrencyRepository;
import com.jaxio.repository.CustomerGenerator;
import com.jaxio.repository.CustomerRepository;
import com.jaxio.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class AccountGenerator {

    /**
     * Returns a new Account instance filled with random values.
     */
    public Account getAccount() {
        Account account = new Account();

        // simple attributes follows
        account.setAccountNumber(ValueGenerator.getUniqueString(100));
        account.setName("a");
        // mandatory relation
        Currency currency = currencyGenerator.getCurrency();
        currencyRepository.save(currency);
        account.setCurrency(currency);
        // mandatory relation
        Customer customer = customerGenerator.getCustomer();
        customerRepository.save(customer);
        account.setCustomer(customer);
        return account;
    }

    @Inject
    private CurrencyRepository currencyRepository;
    @Inject
    private CurrencyGenerator currencyGenerator;
    @Inject
    private CustomerRepository customerRepository;
    @Inject
    private CustomerGenerator customerGenerator;
}