/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.jaxio.web.selenium.page.address;

import static org.openqa.selenium.By.name;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import com.jaxio.web.selenium.support.Page;
import com.jaxio.web.selenium.page.AbstractSearchPage;

@Page
public class AddressSearchPage extends AbstractSearchPage {
    // search box
    @FindBy(id = "form:streetName_input")
    public WebElement streetName;
    @FindBy(id = "form:city_input")
    public WebElement city;

    public void edit(String address) {
        clickEdit(address);
    }

    public void add(String address) {
        clickAdd(address);
    }

    public void delete(String address) {
        clickDelete(address);
        webClient.click(name("form:askForDeleteItemDialogYes"));
    }

    public void select(String address) {
        clickSelect(address);
    }
}