/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/util/IntegrationSampleIT.p.vm.java
 */
package com.jaxio.util;

import static org.fest.assertions.Assertions.assertThat;

import org.junit.Test;

/**
 * Integration test executed by FailSafe plugin
 */
public class IntegrationSampleIT {
    @Test
    public void executedByFailSafePlugin() {
        assertThat(true).isTrue();
    }
}