/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/support/GenericSearchForm.p.vm.java
 */
package com.jaxio.web.domain.support;

import static com.google.common.base.Throwables.propagate;
import static org.apache.commons.io.IOUtils.closeQuietly;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.inject.Inject;

import com.jaxio.dao.support.SearchParameters;
import com.jaxio.domain.Identifiable;
import com.jaxio.domain.SavedSearch;
import com.jaxio.web.conversation.Conversation;
import com.jaxio.web.conversation.ConversationContext;
import com.jaxio.web.conversation.ConversationManager;
import com.jaxio.web.util.MessageUtil;

/**
 * Base Search Form for JPA entities.
 */
public abstract class GenericSearchForm<E extends Identifiable<PK>, PK extends Serializable, F extends GenericSearchForm<E, PK, F>> extends CommonAction<E>
        implements Serializable {
    private static final long serialVersionUID = 1L;

    @Inject
    private transient ConversationManager conversationManager;
    @Inject
    private transient MessageUtil messageUtil;

    @SuppressWarnings("unchecked")
    @PostConstruct
    public void init() {
        Conversation currentConversation = conversationManager.getCurrentConversation();
        if (currentConversation == null) {
            return;
        }

        ConversationContext<?> currentContext = currentConversation.getCurrentContext();
        if (currentContext != null && currentContext.getBean(getPrefilledFormName(), getClass()) != null) {
            resetWithOther((F) currentContext.getBean(getPrefilledFormName(), getClass()));
        }
    }

    public String getPrefilledFormName() {
        return "_" + this.getClass().getName() + "_prefilled_";
    }

    /**
     * Return the entity example used in this search form.
     */
    protected abstract E getEntity();

    /**
     * Always null as we use the setter only to add element.
     */
    public SavedSearch getCurrentSavedSearch() {
        return null;
    }

    public void setCurrentSavedSearch(SavedSearch savedSearch) {
        if (savedSearch != null) {
            messageUtil.info("saved_search_loaded", savedSearch.getName());
            resetWithOther(fromByteArray(savedSearch.getFormContent()));
        }
    }

    protected String searchFormName;

    public String getSearchFormName() {
        return searchFormName;
    }

    public void setSearchFormName(String searchFormName) {
        this.searchFormName = searchFormName;
    }

    private boolean privateSearch;

    public boolean isPrivateSearch() {
        return privateSearch;
    }

    public void setPrivateSearch(boolean privateSearch) {
        this.privateSearch = privateSearch;
    }

    protected String term;

    public String getTerm() {
        return term;
    }

    public void setTerm(String term) {
        this.term = term;
    }

    /**
     * Convert all the search inputs into a @{link SearchParameters}. 
     */
    public abstract SearchParameters toSearchParameters();

    // Reset related

    public abstract F newInstance();

    public abstract void resetWithOther(F other);

    public void reset() {
        messageUtil.info("search_reseted");
        setSearchFormName(null);
        resetWithOther(newInstance());
    }

    protected byte[] toByteArray() {
        ObjectOutputStream oos = null;
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            oos = new ObjectOutputStream(baos);
            oos.writeObject(this);
            oos.flush();
            return baos.toByteArray();
        } catch (Exception e) {
            throw propagate(e);
        } finally {
            closeQuietly(oos);
            closeQuietly(baos);
        }
    }

    @SuppressWarnings("unchecked")
    protected F fromByteArray(byte[] bytes) {
        ObjectInputStream ois = null;
        try {
            ois = new ObjectInputStream(new ByteArrayInputStream(bytes));
            return (F) ois.readObject();
        } catch (Exception e) {
            throw propagate(e);
        } finally {
            closeQuietly(ois);
        }
    }
}
