/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring:src/main/java/domain/EditForm.e.vm.java
 */
package com.jaxio.web.domain.more;

import javax.inject.Inject;
import javax.inject.Named;
import org.springframework.context.annotation.Scope;
import com.jaxio.domain.more.MoreTypesDemo;
import com.jaxio.repository.more.MoreTypesDemoRepository;
import com.jaxio.web.domain.support.GenericEditForm;

/**
 * View Helper to edit {@link MoreTypesDemo}.
 */
@Named
@Scope("conversation")
public class MoreTypesDemoEditForm extends GenericEditForm<MoreTypesDemo, Integer> {
    private MoreTypesDemo moreTypesDemo;

    @Inject
    public void setMoreTypesDemoRepository(MoreTypesDemoRepository moreTypesDemoRepository) {
        setRepository(moreTypesDemoRepository);
    }

    public void setMoreTypesDemo(MoreTypesDemo moreTypesDemo) {
        this.moreTypesDemo = moreTypesDemo;
    }

    public MoreTypesDemo getMoreTypesDemo() {
        return moreTypesDemo;
    }

    @Override
    public MoreTypesDemo getEntity() {
        return moreTypesDemo;
    }

}