/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/domain/Controller.e.vm.java
 */
package com.jaxio.web.domain;

import static com.jaxio.web.util.PrimeFacesUtil.forceClose;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.domain.Address;
import com.jaxio.repository.AddressRepository;
import com.jaxio.web.converter.domain.AddressConverter;
import com.jaxio.web.util.MessageUtil;

/**
 * Thin controller layer allowing you to do business validation and other conditional 
 * checks that are easier to implement in Java than in webflow's xml syntax.
 */
@Named
@Singleton
public class AddressController {
    private static final long serialVersionUID = 1L;

    @Inject
    private AddressRepository addressRepository;

    @Inject
    private MessageUtil messageUtil;

    @Inject
    private AddressConverter addressConverter;

    public Address newIfNull(Address address) {
        if (address != null) {
            return address;
        }

        return addressRepository.getNewWithDefaults();
    }

    public boolean save(Address address) {
        addressRepository.save(address);
        messageUtil.info("status_saved_ok", addressConverter.print(address));
        return true;
    }

    public boolean saveAndClose(Address address) {
        addressRepository.save(address);
        messageUtil.infoDelayed("status_saved_ok", addressConverter.print(address));
        forceClose();
        return true;
    }

    public boolean delete(Address address) {
        String infoArg = addressConverter.print(address);
        addressRepository.delete(address);
        messageUtil.info("status_deleted_ok", infoArg);
        return true;
    }
}