/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/domain/Entity.e.vm.java
 */
package com.jaxio.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;
import org.apache.commons.io.FileUtils;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.ParamDef;
import org.hibernate.validator.constraints.NotEmpty;
import com.google.common.base.Objects;
import com.jaxio.domain.Account;
import com.jaxio.domain.Document_;
import com.jaxio.domain.IdentifiableHashBuilder;

@Entity
@Table(name = "DOCUMENT")
@FilterDef(name = "myDocumentFilter", defaultCondition = "ACCOUNT_ID = :currentAccountId ", parameters = @ParamDef(name = "currentAccountId", type = "org.hibernate.type.StringType"))
@Filter(name = "myDocumentFilter")
public class Document implements Identifiable<String>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Document.class);

    // Raw attributes
    private String id; // pk
    private String documentContentType; // not null
    private Integer documentSize; // not null
    private String documentFileName; // not null
    private byte[] documentBinary;
    private Integer version;

    // Many to one
    private Account account; // not null (accountId)

    // -------------------------------
    // Getter & Setter
    // -------------------------------
    // -- [id] ------------------------

    @Column(name = "ID", length = 36)
    @GeneratedValue(generator = "strategy-uuid2")
    @GenericGenerator(name = "strategy-uuid2", strategy = "uuid2")
    @Id
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Transient
    public boolean isIdSet() {
        return id != null && !id.isEmpty();
    }

    // -- [documentContentType] ------------------------

    @Size(max = 100)
    @NotEmpty
    @Column(name = "DOCUMENT_CONTENT_TYPE", nullable = false, length = 100)
    public String getDocumentContentType() {
        return documentContentType;
    }

    public void setDocumentContentType(String documentContentType) {
        this.documentContentType = documentContentType;
    }

    // -- [documentSize] ------------------------

    @NotNull
    @Column(name = "DOCUMENT_SIZE", nullable = false, precision = 10)
    public Integer getDocumentSize() {
        return documentSize;
    }

    public void setDocumentSize(Integer documentSize) {
        this.documentSize = documentSize;
    }

    // -- [documentFileName] ------------------------

    @Size(max = 100)
    @NotEmpty
    @Column(name = "DOCUMENT_FILE_NAME", nullable = false, length = 100)
    public String getDocumentFileName() {
        return documentFileName;
    }

    public void setDocumentFileName(String documentFileName) {
        this.documentFileName = documentFileName;
    }

    // -- [documentBinary] ------------------------

    @Basic(fetch = FetchType.LAZY)
    @Column(name = "DOCUMENT_BINARY")
    @Lob
    public byte[] getDocumentBinary() {
        return documentBinary;
    }

    public void setDocumentBinary(byte[] documentBinary) {
        this.documentBinary = documentBinary;
    }

    /**
     * Helper method to convert the passed file to a byte[] and set it using {@link #setDocumentBinary(byte[])}
     * @param localFile to read the content from
     * @see #setDocumentBinary(byte[])
     */
    public void setDocumentBinaryFromFile(File localFile) {
        try {
            setDocumentBinary(FileUtils.readFileToByteArray(localFile));
        } catch (Exception e) {
            throw new IllegalStateException("Could not read from file", e);
        }
    }

    /**
     * Helper method to copy documentBinary byte array to the passed target file.
     *
     * @return the passed targetFile as a convenience.
     * @throws IllegalStateException when no binary is set
     * @see #getDocumentBinary()
     */
    @Transient
    @XmlTransient
    public File getDocumentBinaryToFile(File targetFile) throws IOException {
        if (getDocumentBinary() != null) {
            throw new IllegalStateException("Empty binary");
        }

        FileUtils.writeByteArrayToFile(targetFile, getDocumentBinary());
        return targetFile;
    }

    /**
     * Helper method to copy documentBinary byte array to a temporary file.
     *
     * @throws IllegalStateException when no binary is set
     * @return a temporary file holding a copy of the documentBinary byte array
     * @see #getDocumentBinary()
     */
    @Transient
    @XmlTransient
    public File getDocumentBinaryToTempFile() throws IOException {
        return getDocumentBinaryToFile(File.createTempFile("documentBinary", "file"));
    }

    // -- [version] ------------------------

    @Column(name = "VERSION", precision = 10)
    @Version
    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    // --------------------------------------------------------------------
    // Many to One support
    // --------------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Document.accountId ==> Account.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "ACCOUNT_ID", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Account getAccount() {
        return account;
    }

    /**
     * Set the account without adding this Document instance on the passed account
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link Account}
     */
    public void setAccount(Account account) {
        this.account = account;
    }

    /**
     * Set the default values.
     */
    public void initDefaultValues() {
    }

    /**
     * equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Document && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Document instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add(Document_.id.getName(), getId()) //
                .add(Document_.documentContentType.getName(), getDocumentContentType()) //
                .add(Document_.documentSize.getName(), getDocumentSize()) //
                .add(Document_.documentFileName.getName(), getDocumentFileName()) //
                .add(Document_.documentBinary.getName(), getDocumentBinary()) //
                .add(Document_.version.getName(), getVersion()) //
                .toString();
    }
}