/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.jaxio.web.domain;

import static org.apache.commons.lang.StringUtils.join;

import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.domain.Address;
import com.jaxio.web.domain.support.GenericExcelExporter;
import com.jaxio.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Address} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class AddressExcelExporter extends GenericExcelExporter<Address> {
    @Inject
    protected AddressSearchForm sf;

    public AddressExcelExporter() {
        super("address_street", //
                "address_zipCode", //
                "address_city", //
                "address_country");
    }

    @Override
    protected void fillResultItem(int row, Address item) {
        int col = 0;
        setValue(row, col++, item.getStreet());
        setValue(row, col++, item.getZipCode());
        setValue(row, col++, item.getCity());
        setValue(row, col++, item.getCountry());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();
        setLeftHeader(row, 0, "search_full_text");
        setValue(row++, 1, join(sf.getTermsOnAll().getSelected(), ' '));
        setTermSelector(row++, 0, "address_city", sf.getCityTermSelector());
        setTermSelector(row++, 0, "address_country", sf.getCountryTermSelector());

        setSelector(row++, 0, "address_street", sf.getStreetSelector());
        setSelector(row++, 0, "address_zipCode", sf.getZipCodeSelector());
        setSelector(row++, 0, "address_city", sf.getCitySelector());
        setSelector(row++, 0, "address_country", sf.getCountrySelector());
    }
}