/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.jaxio.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;

import com.jaxio.domain.Account;
import com.jaxio.domain.Currency;
import com.jaxio.domain.Transaction;
import com.jaxio.repository.TransactionRepository;
import com.jaxio.web.domain.AccountController;
import com.jaxio.web.domain.CurrencyController;
import com.jaxio.web.domain.TransactionController;
import com.jaxio.web.domain.TransactionGraphLoader;
import com.jaxio.web.domain.support.GenericEditForm;
import com.jaxio.web.domain.support.GenericToOneAssociation;
import com.jaxio.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Transaction}.
 */
@Named
@ConversationContextScoped
public class TransactionEditForm extends GenericEditForm<Transaction, Integer> {
    @Inject
    protected TransactionController transactionController;
    @Inject
    protected CurrencyController currencyController;
    protected GenericToOneAssociation<Currency, Integer> currency;
    @Inject
    protected AccountController accountController;
    protected GenericToOneAssociation<Account, Integer> account;

    @Inject
    public TransactionEditForm(TransactionRepository transactionRepository, TransactionGraphLoader transactionGraphLoader) {
        super(transactionRepository, transactionGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public Transaction getTransaction() {
        return getEntity();
    }

    public String print() {
        return transactionController.print(getTransaction());
    }

    @PostConstruct
    void setupCurrencyActions() {
        currency = new GenericToOneAssociation<Currency, Integer>("transaction_currency", currencyController) {
            @Override
            protected Currency get() {
                return getTransaction().getCurrency();
            }

            @Override
            protected void set(Currency currency) {
                getTransaction().setCurrency(currency);
            }

            @NotNull
            @Override
            public Currency getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Currency, Integer> getCurrency() {
        return currency;
    }

    @PostConstruct
    void setupAccountActions() {
        account = new GenericToOneAssociation<Account, Integer>("transaction_account", accountController) {
            @Override
            protected Account get() {
                return getTransaction().getAccount();
            }

            @Override
            protected void set(Account account) {
                getTransaction().setAccount(account);
            }

            @NotNull
            @Override
            public Account getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Account, Integer> getAccount() {
        return account;
    }
}
