/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.jaxio.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.domain.Transaction;
import com.jaxio.web.domain.support.GenericExcelExporter;
import com.jaxio.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Transaction} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class TransactionExcelExporter extends GenericExcelExporter<Transaction> {
    @Inject
    protected TransactionSearchForm sf;

    public TransactionExcelExporter() {
        super("transaction_account", //
                "transaction_amount", //
                "transaction_transactionDate", //
                "transaction_valueDate", //
                "transaction_description");
    }

    @Override
    protected void fillResultItem(int row, Transaction item) {
        int col = 0;
        setEntity(row, col++, item.getAccount());
        setValue(row, col++, item.getAmount());
        setValue(row, col++, item.getTransactionDate());
        setValue(row, col++, item.getValueDate());
        setValue(row, col++, item.getDescription());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelectedEntities(row++, 0, "transaction_account", sf.getAccountSelector().getSelected());
        setRangeNumber(row++, 0, "transaction_amount", sf.getAmountRange());
        setRange(row++, 0, "transaction_transactionDate", sf.getTransactionDateRange());
        setRange(row++, 0, "transaction_valueDate", sf.getValueDateRange());
        setSelectedEntities(row++, 0, "transaction_currency", sf.getCurrencySelector().getSelected());
        setSelector(row++, 0, "transaction_description", sf.getDescriptionSelector());
    }
}