/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.jaxio.appli.web.selenium.page.account;

import com.jaxio.appli.domain.Civility;
import com.jaxio.appli.web.selenium.support.Page;
import com.jaxio.appli.web.selenium.support.elements.Checkbox;
import com.jaxio.appli.web.selenium.support.elements.ChooseEnum;
import com.jaxio.appli.web.selenium.support.elements.CustomWebElement;
import com.jaxio.appli.web.selenium.support.elements.DateInput;
import com.jaxio.appli.web.selenium.support.elements.EditAction;
import com.jaxio.appli.web.selenium.support.elements.EntityAction;
import com.jaxio.appli.web.selenium.support.elements.Messages;
import com.jaxio.appli.web.selenium.support.elements.NoInverseManyToOne;
import com.jaxio.appli.web.selenium.support.elements.StringInput;
import com.jaxio.appli.web.selenium.support.elements.Tab;

@Page
public class AccountEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public AccountEditForm form;
    public AccountEditTabs tabs;

    public static class AccountEditForm extends CustomWebElement {
        public StringInput username = new StringInput("form:username");
        public StringInput password = new StringInput("form:password");
        public StringInput email = new StringInput("form:email");
        public Checkbox isEnabled = new Checkbox("form:isEnabled");
        public ChooseEnum<Civility> civility = new ChooseEnum<Civility>("form:civility");
        public StringInput firstName = new StringInput("form:firstName");
        public StringInput lastName = new StringInput("form:lastName");
        public DateInput birthDate = new DateInput("form:birthDate");
        public StringInput description = new StringInput("form:description");

        public NoInverseManyToOne homeAddress = new NoInverseManyToOne("form:homeAddress");
    };

    public static class AccountEditTabs extends CustomWebElement {
        public Tab coolBooks = new Tab("book", "coolBooks");
        public Tab edocs = new Tab("edoc", "edocs");
        public Tab securityRoles = new Tab("securityRole", "securityRoles");
    };
}