/*
 * (c) Copyright 2005-2012 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring:src/main/java/converter/JsfConverter.e.vm.java
 */
package com.jaxio.web.converter;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.jaxio.domain.Address;
import com.jaxio.repository.AddressRepository;
import com.jaxio.web.converter.GenericJsfConverter;

/**
 * JSF Converter for {@link Address}.
 */
@Named
@Singleton
public class AddressJsfConverter extends GenericJsfConverter<Address, Integer> {
    @Inject
    public AddressJsfConverter(AddressRepository addressRepository) {
        super(addressRepository, Address.class, Integer.class);
    }
}