/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/converter/JsfConverter.e.vm.java
 */
package com.jaxio.web.converter;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import com.jaxio.domain.Legacy;
import com.jaxio.domain.LegacyPk;
import com.jaxio.repository.LegacyRepository;
import com.jaxio.web.converter.support.GenericJsfConverter;

/**
 * JSF converter for {@link Legacy}.
 * @see GenericJsfConverter
 */
@Named
@Singleton
public class LegacyJsfConverter extends GenericJsfConverter<Legacy, LegacyPk> {
    @Inject
    public LegacyJsfConverter(LegacyRepository legacyRepository) {
        super(legacyRepository, Legacy.class, LegacyPk.class);
    }

    @Override
    public LegacyPk toPk(String pkAsString) {
        return LegacyPk.fromString(pkAsString);
    }
}