/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/configuration/ViewScopeConfiguration.p.vm.java
 */
package com.jaxio.appli.web.configuration;

import static com.google.common.collect.Maps.newHashMap;

import java.util.Map;

import org.springframework.beans.factory.config.CustomScopeConfigurer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.jaxio.appli.web.faces.ConversationContextScope;
import com.jaxio.appli.web.faces.ConversationScope;
import com.jaxio.appli.web.faces.ViewScope;

@Configuration
public class ViewScopeConfiguration {
    @Bean
    public static CustomScopeConfigurer viewScope() {
        CustomScopeConfigurer scope = new CustomScopeConfigurer();
        Map<String, Object> map = newHashMap();
        map.put("view", new ViewScope());
        map.put("conversationContext", new ConversationContextScope());
        map.put("conversation", new ConversationScope());
        scope.setScopes(map);
        return scope;
    }
}