/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces-sd:src/main/java/flow/DomainFactory.p.vm.java
 */
package com.jaxio.demo.web.flow;

import org.springframework.stereotype.Component;

import com.jaxio.demo.domain.Account;
import com.jaxio.demo.domain.Address;
import com.jaxio.demo.domain.Book;
import com.jaxio.demo.domain.Document;
import com.jaxio.demo.domain.Legacy;
import com.jaxio.demo.domain.more.MoreTypesDemo;
import com.jaxio.demo.domain.Role;

/**
 * Helper used from Spring Web Flow scripts to create new entity instance.
 */
@Component
public class DomainFactory {
    public Account getNewAccount() {
        return new Account();
    }

    public Address getNewAddress() {
        return new Address();
    }

    public Book getNewBook() {
        return new Book();
    }

    public Document getNewDocument() {
        return new Document();
    }

    public Legacy getNewLegacy() {
        return new Legacy();
    }

    public MoreTypesDemo getNewMoreTypesDemo() {
        return new MoreTypesDemo();
    }

    public Role getNewRole() {
        return new Role();
    }
}