/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/dao/DAOImpl.e.vm.java
 */
package com.jaxio.dao;

import javax.inject.Named;
import javax.inject.Singleton;
import com.jaxio.dao.LegacyDao;
import com.jaxio.dao.support.GenericDao;
import com.jaxio.domain.Legacy;
import com.jaxio.domain.LegacyPk;

/**
 * JPA 2 Data Access Object for {@link com.jaxio.domain.Legacy}.
 * Note: do not use @Transactional in the DAO layer.
 */
@Named
@Singleton
public class LegacyDao extends GenericDao<Legacy, LegacyPk> {
    public LegacyDao() {
        super(Legacy.class);
    }

}