/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.jaxio.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import com.jaxio.domain.Address;
import com.jaxio.repository.AddressRepository;
import com.jaxio.web.domain.AddressController;
import com.jaxio.web.domain.support.GenericEditForm;
import com.jaxio.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Address}.
 */
@Named
@ConversationContextScoped
public class AddressEditForm extends GenericEditForm<Address, Integer> {
    @Inject
    protected AddressController addressController;

    @Inject
    public AddressEditForm(AddressRepository addressRepository) {
        super(addressRepository);
    }

    /**
     * The entity to edit/view.
     */
    public Address getAddress() {
        return getEntity();
    }

    public String print() {
        return addressController.print(getAddress());
    }
}
