/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.jaxio.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;
import javax.servlet.http.HttpServletRequest;
import com.jaxio.domain.Book;
import com.jaxio.repository.BookRepository;
import com.jaxio.web.conversation.Conversation;
import com.jaxio.web.conversation.ConversationContext;
import com.jaxio.web.conversation.ConversationFactory;
import com.jaxio.web.domain.support.GenericController;
import com.jaxio.web.permission.BookPermission;

/**
 * Stateless controller for Book conversation start. Provides also auto-complete support. 
 */
@Named
@Singleton
public class BookController extends GenericController<Book, Integer> implements ConversationFactory {
    public final static String editUri = "/domain/bookEdit.faces";
    public final static String selectUri = "/domain/bookSelect.faces";

    @Inject
    public BookController(BookRepository bookRepository, BookPermission bookPermission) {
        super(bookRepository, bookPermission);
    }

    // -------------------
    // ConversationFactory
    // -------------------

    @Override
    public boolean canCreateConversation(HttpServletRequest request) {
        return selectUri.equals(request.getServletPath()) || editUri.equals(request.getServletPath());
    }

    @Override
    public Conversation createConversation(HttpServletRequest request) {
        String uri = request.getServletPath();
        if (selectUri.equals(uri)) {
            return Conversation.newConversation(request, newSearchContext("book"));
        } else if (editUri.equals(uri)) {
            return Conversation.newConversation(request, newEditContext("book", new Book()));
        } else {
            throw new IllegalStateException("Unexpected conversation creation demand");
        }
    }

    // --------------------------------
    // Helper 
    // --------------------------------    

    /**
     * Helper to construct a new ConversationContext to edit an Book.
     * @param book the entity to edit.
     */
    public ConversationContext<Book> newEditContext(final Book book) {
        ConversationContext<Book> ctx = new ConversationContext<Book>();
        ctx.setEntity(book); // used by GenericEditForm.init()
        ctx.setIsNewEntity(!book.isIdSet());
        ctx.setViewUri(editUri);
        return ctx;
    }

    /**
     * Helper to construct a new ConversationContext for search/selection.
     */
    public ConversationContext<Book> newSearchContext() {
        ConversationContext<Book> ctx = new ConversationContext<Book>();
        ctx.setViewUri(selectUri);
        return ctx;
    }
}