/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-spring:src/main/java/domain/Context.e.vm.java
 */
package com.jaxio.web.domain;

import com.jaxio.domain.Document;
import com.jaxio.web.conversation.ConversationContext;

/**
 * The context for {@link Account} edit/select views.
 */
public class DocumentContext extends ConversationContext<Document> {
    private static final long serialVersionUID = 1L;
    public final static String editUri = "/domain/documentEdit.faces";
    public final static String selectUri = "/domain/documentSelect.faces";

    public DocumentContext() {
    }

    public DocumentContext(Document document) {
        setVar("document", document);
    }

    /**
     * Developer friendly method to get the entity. Use it from Java code for better clarity.
     */
    public Document getDocument() {
        return getEntity();
    }

    @Override
    public Document getEntity() {
        return getVar("document", Document.class);
    }
}
