/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/AbstractSearchPage.p.vm.java
 */
package fr.jaxio.demo.web.selenium.page;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import fr.jaxio.demo.web.selenium.support.Client;

public abstract class AbstractSearchPage {
    // header
    @FindBy(id = "form:cancel")
    public WebElement backButton;
    @FindBy(id = "form:quit")
    public WebElement quitButton;
    @FindBy(id = "form:sendNew")
    public WebElement newButton;

    // search box
    @FindBy(id = "form:search")
    public WebElement searchButton;

    // sum
    @FindBy(id = "searchResultsRegion")
    public WebElement searchResultsRegion;

    // paginator
    @FindBy(css = "span.ui-paginator-current")
    public WebElement paginatorText;
    @FindBy(css = "span.ui-icon-seek-next")
    public WebElement paginatorNextButton;
    @FindBy(css = "span.ui-icon-seek-prev")
    public WebElement paginatorPrevButton;

    protected Client client;
}
