/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/permission/Permission.e.vm.java
 */
package com.jaxio.appli.web.permission;

import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.appli.domain.Account;
import com.jaxio.appli.web.permission.support.GenericPermission;

@Named
@Singleton
public class AccountPermission extends GenericPermission<Account> {
    public AccountPermission() {
        super(Account.class);
    }
}