/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/support/Ranges.p.vm.java
 */
package com.jaxio.repository.support;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

import javax.persistence.metamodel.Attribute;

import org.joda.time.LocalDate;
import org.joda.time.LocalDateTime;

/**
 * Type safe {@link Range}s for commons types
 */
public class Ranges {
    public static class RangeInteger<E> extends Range<E, Integer> {
        private static final long serialVersionUID = 1L;

        public RangeInteger(Attribute<?, ?>... fields) {
            super(fields);
        }

        public static <E> RangeInteger<E> newRangeInteger(Attribute<?, ?>... fields) {
            return new RangeInteger<E>(fields);
        }
    }

    public static class RangeBigInteger<E> extends Range<E, BigInteger> {
        private static final long serialVersionUID = 1L;

        public RangeBigInteger(Attribute<?, ?>... fields) {
            super(fields);
        }

        public static <E> RangeBigInteger<E> newRangeBigInteger(Attribute<?, ?>... fields) {
            return new RangeBigInteger<E>(fields);
        }
    }

    public static class RangeLong<E> extends Range<E, Long> {
        private static final long serialVersionUID = 1L;

        public RangeLong(Attribute<?, ?>... fields) {
            super(fields);
        }

        public static <E> RangeLong<E> newRangeLong(Attribute<?, ?>... fields) {
            return new RangeLong<E>(fields);
        }
    }

    public static class RangeDouble<E> extends Range<E, Double> {
        private static final long serialVersionUID = 1L;

        public RangeDouble(Attribute<?, ?>... fields) {
            super(fields);
        }

        public static <E> RangeDouble<E> newRangeDouble(Attribute<?, ?>... fields) {
            return new RangeDouble<E>(fields);
        }
    }

    public static class RangeFloat<E> extends Range<E, Float> {
        private static final long serialVersionUID = 1L;

        public RangeFloat(Attribute<?, ?>... fields) {
            super(fields);
        }

        public static <E> RangeFloat<E> newRangeFloat(Attribute<?, ?>... fields) {
            return new RangeFloat<E>(fields);
        }
    }

    public static class RangeBigDecimal<E> extends Range<E, BigDecimal> {
        private static final long serialVersionUID = 1L;

        public RangeBigDecimal(Attribute<?, ?>... fields) {
            super(fields);
        }

        public static <E> RangeBigDecimal<E> newRangeBigDecimal(Attribute<?, ?>... fields) {
            return new RangeBigDecimal<E>(fields);
        }
    }

    public static class RangeDate<E> extends Range<E, Date> {
        private static final long serialVersionUID = 1L;

        public RangeDate(Attribute<?, ?>... fields) {
            super(fields);
        }

        public static <T> RangeDate<T> newRangeDate(Attribute<?, ?>... fields) {
            return new RangeDate<T>(fields);
        }
    }

    public static class RangeLocalDate<E> extends Range<E, LocalDate> {
        private static final long serialVersionUID = 1L;

        public RangeLocalDate(Attribute<?, ?>... fields) {
            super(fields);
        }

        public static <E> RangeLocalDate<E> newRangeLocalDate(Attribute<?, ?>... fields) {
            return new RangeLocalDate<E>(fields);
        }
    }

    public static class RangeLocalDateTime<E> extends Range<E, LocalDateTime> {
        private static final long serialVersionUID = 1L;

        public RangeLocalDateTime(Attribute<?, ?>... fields) {
            super(fields);
        }

        public static <E> RangeLocalDateTime<E> newRangeLocalDateTime(Attribute<?, ?>... fields) {
            return new RangeLocalDateTime<E>(fields);
        }
    }
}