/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.jaxio.appli.web.selenium.page.auditlog;

import com.jaxio.appli.web.selenium.support.Page;
import com.jaxio.appli.web.selenium.support.elements.Autocomplete;
import com.jaxio.appli.web.selenium.support.elements.CustomWebElement;
import com.jaxio.appli.web.selenium.support.elements.EntityAction;
import com.jaxio.appli.web.selenium.support.elements.Messages;
import com.jaxio.appli.web.selenium.support.elements.OrderBy;
import com.jaxio.appli.web.selenium.support.elements.SearchForm;
import com.jaxio.appli.web.selenium.support.elements.StringRange;
import com.jaxio.appli.web.selenium.support.elements.Table;

@Page
public class AuditLogSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public AuditLogSearchOrders orders;
    public AuditLogSearchForm form;

    public static class AuditLogSearchOrders extends CustomWebElement {
        public OrderBy author = new OrderBy("auditLog_author");
        public OrderBy event = new OrderBy("auditLog_event");
        public OrderBy eventDate = new OrderBy("auditLog_eventDate");
        public OrderBy stringAttribute1 = new OrderBy("auditLog_stringAttribute1");
        public OrderBy stringAttribute2 = new OrderBy("auditLog_stringAttribute2");
        public OrderBy stringAttribute3 = new OrderBy("auditLog_stringAttribute3");
    }

    public static class AuditLogSearchForm extends SearchForm {
        public Autocomplete author = new Autocomplete("form:author");
        public Autocomplete event = new Autocomplete("form:event");
        public StringRange eventDate = new StringRange("form:eventDate");
        public Autocomplete stringAttribute1 = new Autocomplete("form:stringAttribute1");
        public Autocomplete stringAttribute2 = new Autocomplete("form:stringAttribute2");
        public Autocomplete stringAttribute3 = new Autocomplete("form:stringAttribute3");
    }
}