/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.jaxio.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.domain.Currency;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class CurrencyGenerator {

    /**
     * Returns a new Currency instance filled with random values.
     */
    public Currency getCurrency() {
        Currency currency = new Currency();

        // simple attributes follows
        currency.setCode("ddd");
        currency.setName("a");
        currency.setDecimalCount(1);
        return currency;
    }

}