/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/RepositoryTest.e.vm.java
 */
package com.jaxio.repository;

import static org.fest.assertions.Assertions.assertThat;
import static org.mockito.Matchers.any;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import javax.persistence.NoResultException;
import javax.persistence.NonUniqueResultException;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

import com.jaxio.dao.CustomerDao;
import com.jaxio.dao.support.SearchParameters;
import com.jaxio.domain.Customer;
import com.jaxio.repository.CustomerRepository;

/**
 * Unit test on CustomerRepository
 */
@RunWith(MockitoJUnitRunner.class)
public class CustomerRepositoryTest {

    @Mock
    private CustomerDao customerDao;

    @InjectMocks
    private CustomerRepository customerRepository;

    @Test
    public void findUniqueOrNoneReturnsNull() {
        when(customerDao.findUniqueOrNone(any(Customer.class), any(SearchParameters.class))).thenReturn(null);

        Customer result = customerRepository.findUniqueOrNone(new Customer());

        assertThat(result).isNull();
        verify(customerDao, times(1)).findUniqueOrNone(any(Customer.class), any(SearchParameters.class));
    }

    @Test
    public void findUniqueOrNoneReturnsSingleValue() {
        Customer unique = new Customer();

        when(customerDao.findUniqueOrNone(any(Customer.class), any(SearchParameters.class))).thenReturn(unique);

        Customer result = customerRepository.findUniqueOrNone(new Customer());

        assertThat(result).isNotNull().isSameAs(unique);
        verify(customerDao, times(1)).findUniqueOrNone(any(Customer.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void findUniqueOrNoneThrowsExceptionWhenNonUniqueResults() {
        when(customerDao.findUniqueOrNone(any(Customer.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        customerRepository.findUniqueOrNone(new Customer());
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NoResultException.class)
    public void findUniqueThrowsExceptionWhenNoResult() {
        when(customerDao.findUnique(any(Customer.class), any(SearchParameters.class))).thenThrow(NoResultException.class);

        customerRepository.findUnique(new Customer());
    }

    @Test
    public void findUnique() {
        Customer unique = new Customer();

        when(customerDao.findUnique(any(Customer.class), any(SearchParameters.class))).thenReturn(unique);

        Customer result = customerRepository.findUnique(new Customer());

        assertThat(result).isNotNull();
        verify(customerDao, times(1)).findUnique(any(Customer.class), any(SearchParameters.class));
    }

    @SuppressWarnings("unchecked")
    @Test(expected = NonUniqueResultException.class)
    public void findUniqueThrowsExeptionWhenNonUniqueResult() {
        when(customerDao.findUnique(any(Customer.class), any(SearchParameters.class))).thenThrow(NonUniqueResultException.class);

        customerRepository.findUnique(new Customer());
    }
}