/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.jaxio.web.selenium.page.transaction;

import com.jaxio.web.selenium.support.Page;
import com.jaxio.web.selenium.support.elements.CustomWebElement;
import com.jaxio.web.selenium.support.elements.DateInput;
import com.jaxio.web.selenium.support.elements.EditAction;
import com.jaxio.web.selenium.support.elements.EntityAction;
import com.jaxio.web.selenium.support.elements.IntegerInput;
import com.jaxio.web.selenium.support.elements.ManyToOne;
import com.jaxio.web.selenium.support.elements.Messages;
import com.jaxio.web.selenium.support.elements.NoInverseManyToOne;
import com.jaxio.web.selenium.support.elements.StringInput;

@Page
public class TransactionEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public TransactionEditForm form;
    public TransactionEditTabs tabs;

    public static class TransactionEditForm extends CustomWebElement {
        public IntegerInput amount = new IntegerInput("form:amount");
        public DateInput transactionDate = new DateInput("form:transactionDate");
        public DateInput valueDate = new DateInput("form:valueDate");
        public StringInput description = new StringInput("form:description");

        public NoInverseManyToOne currency = new NoInverseManyToOne("form:currency");

        public ManyToOne account = new ManyToOne("form:account");
    };

    public static class TransactionEditTabs extends CustomWebElement {
    };
}