/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/service/Service.e.vm.java
 */
package fr.jaxio.demo.service;

import fr.jaxio.demo.domain.Address;
import fr.jaxio.demo.service.support.GenericEntityService;

/**
 * The AddressService is a data-centric service for the {@link Address} entity.
 * It provides the expected methods to get/delete a {@link Address} instance
 * plus some methods to perform searches.
 * <p>
 * Search logic is driven by 2 kinds of parameters: a {@link Address} instance used
 * as a properties holder against which the search will be performed and a {@link SearchParameters}
 * instance from where you can control your search options including the usage
 * of named queries.
 */
public interface AddressService extends GenericEntityService<Address, Integer> {
}