/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/service/ServiceImpl.e.vm.java
 */
package fr.jaxio.demo.service;

import javax.inject.Inject;

import org.apache.log4j.Logger;

import javax.inject.Named;
import javax.inject.Singleton;

import fr.jaxio.demo.dao.support.GenericDao;
import fr.jaxio.demo.service.support.GenericEntityServiceImpl;
import fr.jaxio.demo.domain.Legacy;
import fr.jaxio.demo.domain.LegacyPk;
import fr.jaxio.demo.dao.LegacyDao;

/**
 * Default implementation of the {@link LegacyService} interface.
 * Note: you may use multiple DAO from this layer.
 * @see LegacyService
 */
@Named("legacyService")
@Singleton
public class LegacyServiceImpl extends GenericEntityServiceImpl<Legacy, LegacyPk> implements LegacyService {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(LegacyServiceImpl.class);

    protected LegacyDao legacyDao;

    @Inject
    public void setLegacyDao(LegacyDao legacyDao) {
        this.legacyDao = legacyDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<Legacy, LegacyPk> getDao() {
        return legacyDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Legacy getNew() {
        return new Legacy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Legacy getNewWithDefaults() {
        Legacy result = getNew();
        result.initDefaultValues();
        return result;
    }

}