/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/converter/EntityConverter.e.vm.java
 */
package com.jaxio.web.converter.domain;

import javax.inject.Inject;
import org.springframework.stereotype.Component;
import com.jaxio.domain.Address;
import com.jaxio.repository.AddressRepository;
import com.jaxio.web.converter.GenericJsfConverter;

/**
 * Responsible for creating Address JSF converters.
 * Each converter provides a 'print' method to convert an entity instance to a friendly string representation (readable by humans...).
 */
@Component
public class AddressConverter extends GenericJsfConverter<Address, Integer> {
    @Inject
    public AddressConverter(AddressRepository addressRepository) {
        super(addressRepository, Integer.class);
    }

    @Override
    public String print(Address address) {
        return address == null ? "" : "" + address.getCity();
    }
}