/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/converter/EntityConverter.e.vm.java
 */
package com.jaxio.web.converter.domain;

import javax.inject.Inject;
import org.springframework.stereotype.Component;
import com.jaxio.domain.Legacy;
import com.jaxio.domain.LegacyPk;
import com.jaxio.repository.LegacyRepository;
import com.jaxio.web.converter.GenericJsfConverter;

/**
 * Responsible for creating Legacy JSF converters.
 * Each converter provides a 'print' method to convert an entity instance to a friendly string representation (readable by humans...).
 */
@Component
public class LegacyConverter extends GenericJsfConverter<Legacy, LegacyPk> {
    @Inject
    public LegacyConverter(LegacyRepository legacyRepository) {
        super(legacyRepository, LegacyPk.class);
    }

    @Override
    public String print(Legacy legacy) {
        return legacy == null ? "" : "" + legacy.getExtraInfo();
    }
}