/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.jaxio.web.selenium.page.savedsearch;

import com.jaxio.web.selenium.support.Page;
import com.jaxio.web.selenium.support.elements.Autocomplete;
import com.jaxio.web.selenium.support.elements.CustomWebElement;
import com.jaxio.web.selenium.support.elements.EntityAction;
import com.jaxio.web.selenium.support.elements.Messages;
import com.jaxio.web.selenium.support.elements.OrderBy;
import com.jaxio.web.selenium.support.elements.SearchForm;
import com.jaxio.web.selenium.support.elements.Table;

@Page
public class SavedSearchSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public SavedSearchSearchOrders orders;
    public SavedSearchSearchForm form;

    public static class SavedSearchSearchOrders extends CustomWebElement {
        public OrderBy name = new OrderBy("savedSearch_name");
        public OrderBy formClassname = new OrderBy("savedSearch_formClassname");
        public OrderBy formContent = new OrderBy("savedSearch_formContent");
        public OrderBy userId = new OrderBy("savedSearch_userId");
    }

    public static class SavedSearchSearchForm extends SearchForm {
        public Autocomplete name = new Autocomplete("form:name");
        public Autocomplete formClassname = new Autocomplete("form:formClassname");
        public Autocomplete user = new Autocomplete("form:userSelector");
    }
}