/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.jaxio.web.selenium.page.account;

import static org.openqa.selenium.By.cssSelector;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import com.jaxio.web.selenium.support.Page;
import com.jaxio.web.selenium.page.AbstractSearchPage;

@Page
public class AccountSearchPage extends AbstractSearchPage {
    // search box
    @FindBy(id = "form:username")
    public WebElement username;
    @FindBy(id = "form:password")
    public WebElement password;
    @FindBy(id = "form:email")
    public WebElement email;
    @FindBy(id = "form:isEnabled")
    public WebElement isEnabled;
    @FindBy(id = "form:civility")
    public WebElement civility;
    @FindBy(id = "form:firstName")
    public WebElement firstName;
    @FindBy(id = "form:lastName")
    public WebElement lastName;
    @FindBy(id = "form:birthDate")
    public WebElement birthDate;
    @FindBy(id = "form:description")
    public WebElement description;
    @FindBy(id = "form:homeAddress")
    public WebElement homeAddress;

    public void clickEditAccount(String account) {
        client.click(cssSelector("button[title=\"Edit " + account + "\"]"));
    }

    public void clickAddAccount(String account) {
        client.click(cssSelector("button[title=\"Add " + account + "\"]"));
    }

    public void clickDeleteAccount(String account) {
        client.click(cssSelector("button[title=\"Delete " + account + "\"]"));
    }

    public void clickSelectAccount(String account) {
        client.click(cssSelector("button[title=\"Select " + account + "\"]"));
    }

    public void searchByUsername(String _username) {
        client.clear(email, password, username);
        client.fill(username, _username);
        client.click(searchButton);
    }

    public void searchByEmail(String _email) {
        client.clear(password, username);
        client.fill(email, _email);
        client.click(searchButton);
    }
}