/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.jaxio.appli.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.appli.domain.Legacy;
import com.jaxio.appli.domain.LegacyPk;
import com.jaxio.appli.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link Legacy} 
 */
@Named
@Singleton
public class LegacyRepository extends GenericRepository<Legacy, LegacyPk> {

    public LegacyRepository() {
        super(Legacy.class);
    }

    @Override
    public Legacy getNew() {
        return new Legacy();
    }

    @Override
    public Legacy getNewWithDefaults() {
        return getNew().withDefaults();
    }
}