/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.jaxio.appli.web.domain;

import static com.jaxio.appli.repository.support.PropertySelector.newPropertySelector;

import javax.inject.Named;

import com.jaxio.appli.domain.Address;
import com.jaxio.appli.domain.Address_;
import com.jaxio.appli.repository.support.PropertySelector;
import com.jaxio.appli.repository.support.SearchParameters;
import com.jaxio.appli.repository.support.TermSelector;
import com.jaxio.appli.web.domain.support.GenericSearchForm;
import com.jaxio.appli.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Address}.
 * It exposes a {@link Address} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class AddressSearchForm extends GenericSearchForm<Address, Integer, AddressSearchForm> {
    private static final long serialVersionUID = 1L;

    // full text search (applied first)
    protected TermSelector cityTermSelector = new TermSelector(Address_.city);

    // classic search
    protected Address address = new Address();
    protected PropertySelector<Address, String> streetNameSelector = newPropertySelector(Address_.streetName);
    protected PropertySelector<Address, String> citySelector = newPropertySelector(Address_.city);

    public Address getAddress() {
        return address;
    }

    @Override
    protected Address getEntity() {
        return getAddress();
    }

    @Override
    public AddressSearchForm newInstance() {
        return new AddressSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.term(termsOnAll, cityTermSelector);
        sp.property(streetNameSelector, citySelector);
        return sp;
    }

    @Override
    public void resetWithOther(AddressSearchForm other) {
        this.address = other.getAddress();
        this.termsOnAll = other.getTermsOnAll();
        this.cityTermSelector = other.getCityTermSelector();
        this.streetNameSelector = other.getStreetNameSelector();
        this.citySelector = other.getCitySelector();
    }

    // Term selectors    
    public TermSelector getCityTermSelector() {
        return cityTermSelector;
    }

    // Property selectors
    public PropertySelector<Address, String> getStreetNameSelector() {
        return streetNameSelector;
    }

    public PropertySelector<Address, String> getCitySelector() {
        return citySelector;
    }
}
