/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 */
package com.jaxio.appli.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.appli.domain.Document;
import com.jaxio.appli.repository.DocumentRepository;
import com.jaxio.appli.repository.support.EntityGraphLoader;

/**
 * Preloads the {@link Document} associations required by the view layer.
 * 
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@Named
@Singleton
public class DocumentGraphLoader extends EntityGraphLoader<Document, String> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected DocumentGraphLoader() {
        super();
    }

    @Inject
    public DocumentGraphLoader(DocumentRepository documentRepository) {
        super(documentRepository);
    }

    @Override
    public void loadGraph(Document document) {
        loadSingular(document.getOwner());
    }
}