/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.jaxio.appli.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.appli.domain.Role;
import com.jaxio.appli.domain.Role_;
import com.jaxio.appli.printer.RolePrinter;
import com.jaxio.appli.repository.RoleRepository;
import com.jaxio.appli.repository.support.SearchParameters;
import com.jaxio.appli.web.domain.support.GenericController;
import com.jaxio.appli.web.permission.RolePermission;

/**
 * Stateless controller for {@link Role} conversation start.
 */
@Named
@Singleton
public class RoleController extends GenericController<Role, Integer> {
    public static final String ROLE_EDIT_URI = "/domain/roleEdit.faces";
    public static final String ROLE_SELECT_URI = "/domain/roleSelect.faces";

    @Inject
    public RoleController(RoleRepository roleRepository, RolePermission rolePermission, RolePrinter rolePrinter) {
        super(roleRepository, rolePermission, rolePrinter, ROLE_SELECT_URI, ROLE_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(Role_.roleName);
    }
}