/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.jaxio.web.selenium.page.user;

import com.jaxio.domain.Civility;
import com.jaxio.web.selenium.support.Page;
import com.jaxio.web.selenium.support.elements.Autocomplete;
import com.jaxio.web.selenium.support.elements.ChooseEnum;
import com.jaxio.web.selenium.support.elements.CustomElement;
import com.jaxio.web.selenium.support.elements.EntityAction;
import com.jaxio.web.selenium.support.elements.ManyBooleans;
import com.jaxio.web.selenium.support.elements.Messages;
import com.jaxio.web.selenium.support.elements.OrderBy;
import com.jaxio.web.selenium.support.elements.SearchForm;
import com.jaxio.web.selenium.support.elements.Table;

@Page
public class UserSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public UserSearchOrders orders;
    public UserSearchForm form;

    public static class UserSearchOrders extends CustomElement {
        public OrderBy username = new OrderBy("user_username");
        public OrderBy password = new OrderBy("user_password");
        public OrderBy email = new OrderBy("user_email");
        public OrderBy isEnabled = new OrderBy("user_isEnabled");
        public OrderBy civility = new OrderBy("user_civility");
        public OrderBy firstName = new OrderBy("user_firstName");
        public OrderBy lastName = new OrderBy("user_lastName");
    }

    public static class UserSearchForm extends SearchForm {
        public Autocomplete username = new Autocomplete("form:username");
        public Autocomplete password = new Autocomplete("form:password");
        public Autocomplete email = new Autocomplete("form:email");
        public ManyBooleans isEnabled = new ManyBooleans("form:isEnabled");
        public ChooseEnum<Civility> civility = new ChooseEnum<Civility>("form:civility");
        public Autocomplete firstName = new Autocomplete("form:firstName");
        public Autocomplete lastName = new Autocomplete("form:lastName");
        public Autocomplete securityRoles = new Autocomplete("form:securityRolesSelector");
    }
}