/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/dao/DaoIT.e.vm.java
 */
package com.jaxio.dao;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.jaxio.domain.Document;
import com.jaxio.repository.DocumentGenerator;
import com.jaxio.dao.DocumentDao;

/**
 * Integration test on DocumentDao
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class DocumentDaoIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(DocumentDaoIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private DocumentDao documentDao;

    @Inject
    private DocumentGenerator documentGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Document document = documentGenerator.getDocument();

        // add it to a Set before saving (force equals/hashcode)
        Set<Document> set = newHashSet(document, document);
        assertThat(set).hasSize(1);

        documentDao.save(document);
        entityManager.flush();

        // reload it from cache and check equality
        Document model = new Document();
        model.setId(document.getId());
        assertThat(document).isEqualTo(documentDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(document.getId()).isEqualTo(documentDao.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(document).isNotEqualTo(documentDao.get(model));
    }
}