/*
 * (c) Copyright 2005-2012 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-jpa:src/main/java/project/repository/Repository.e.vm.java
 */
package fr.bdf.repository.more;

import fr.bdf.domain.more.MoreTypesDemo;
import fr.bdf.repository.support.Repository;

/**
 * The MoreTypesDemoRepository is a data-centric service for the {@link MoreTypesDemo} entity.
 * It provides the expected methods to get/delete a {@link MoreTypesDemo} instance
 * plus some methods to perform searches.
 * <p>
 * Search logic is driven by 2 kinds of parameters: a {@link MoreTypesDemo} instance used
 * as a properties holder against which the search will be performed and a {@link SearchParameters}
 * instance from where you can control your search options including the usage
 * of named queries.
 */
public interface MoreTypesDemoRepository extends Repository<MoreTypesDemo, Integer> {
}