/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces:src/main/java/component/LenientBeanValidator.p.vm.java
 */
package com.jaxio.web.component;

import java.util.Map;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.BeanValidator;

import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * Disables validation for certain actions in order to let the user navigate to sub view
 * without loosing (potentially invalid) data entered in input fields.
 * 
 * _HACK_ This setting is tricky. It circumvents a JSF limitation.
 */
@Component
@Scope(BeanDefinition.SCOPE_PROTOTYPE)
public class LenientBeanValidator extends BeanValidator {
    @Override
    public void validate(FacesContext context, UIComponent component, Object value) {
        if (doValidation(context)) {
            super.validate(context, component, value);
        }
    }

    private boolean doValidation(FacesContext context) {
        Map<String, String[]> requestParameterValuesMap = context.getExternalContext().getRequestParameterValuesMap();
        // save button present in main form (see saveButton.xml)
        if (requestParameterValuesMap.containsKey("form:save")) {
            return true;
        }

        // saveAndClose button present in main form (see saveButton.xml)
        if (requestParameterValuesMap.containsKey("form:saveAndClose")) {
            return true;
        }

        // askForSaveDialogYes button present in ask for save dialog
        if (requestParameterValuesMap.containsKey("form:askForSaveDialogYes")) {
            return true;
        }

        // ok button present in sub-edit (see saveButton.xml)
        if (requestParameterValuesMap.containsKey("form:ok")) {
            return true;
        }

        return false;
    }
}
