/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/project/repository/Repository.e.vm.java
 */
package com.jaxio.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.dao.CustomerDao;
import com.jaxio.domain.Customer;
import com.jaxio.repository.support.GenericRepository;

@Named
@Singleton
public class CustomerRepository extends GenericRepository<Customer, Integer> {

    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected CustomerRepository() {
        super();
    }

    @Inject
    public CustomerRepository(CustomerDao customerDao) {
        super(customerDao);
    }

    @Override
    public Customer getNew() {
        return new Customer();
    }

    @Override
    public Customer getNewWithDefaults() {
        Customer result = getNew();
        result.initDefaultValues();
        return result;
    }
}